### ISSUE TITLE
cli-runtime?

### ISSUE THREAD

**Issue by ahmetb** [superbrothers/ksort#20]
I think this project should use https://github.com/kubernetes/cli-runtime/blob/92d2de416dd7c9e51c979d04b1d305a396a13ce6/pkg/genericclioptions/filename_flags.go flags like `-f` and `-R` so that it feels like kubectl, e.g.

    ksort -R -f ./manifests | kubectl apply -f-

wdyt?

**Comment by superbrothers** [comment]
Thank you for suggestion. Sound good to me! I'll change it.
