### ISSUE TITLE
Use tar.gz to publish the release binaries.

### ISSUE THREAD

**Issue by h0tbird** [superbrothers/ksort#32]
Thank you for `ksort`!
Would you consider publishing the release binaries in `tar.gz` format?

**Comment by superbrothers** [comment]
OK! I'll publish the release binaries in `tar.gz` format.

**Comment by superbrothers** [comment]
I released ksort v0.3.1, and published binary files in `tar.gz` format! Enjoy!  https://github.com/superbrothers/ksort/releases/tag/v0.3.1

**Comment by h0tbird** [comment]
Thank you! 👏
